import config from "./config";

const assets = {
  nav: {
    transparentLogoWhite:
      config.assetBaseUrl + "/5rc/nav/transparent-icon-white.webp",
    cart: config.assetBaseUrl + "/5rc/nav/cart.svg",
  },
  home: {
    desktopHeroImg: config.assetBaseUrl + "/5rc/home/dt.webp",
    heroGif: config.assetBaseUrl + "/5rc/home/example-hero.gif",
    mobileBgWebm: config.assetBaseUrl + "/5rc/home/mobile.webm",
    mobileBgMp4: config.assetBaseUrl + "/5rc/home/mobile.mp4",
  },
  terms: {
    version: "1.0",
    text: [
      "Welcome to 5th Round Cardio, LLC. By accessing or using our products and services, you agree to be bound by the following terms and conditions. Please read them carefully.",
      "",
      "1. General",
      "",
      "  1.1 These Terms govern your use of our products (collectively, the “Product”), website, and any related services offered by 5th Round Cardio, LLC (the “Service”).",
      "",
      "  1.2 By accessing or using the Product and/or Service, you agree to be bound by these Terms. If you disagree with any part of the Terms, you may not access or use the Service.",
      "",
      "2. Content",
      "",
      "  2.1 The Service may contain content owned by us or licensed to us (the “Content”).",
      "",
      "  2.2 The Content is protected by copyright, trademark, and other intellectual property laws.",
      "",
      "  2.3 You agree not to modify, reproduce, distribute, or create derivative works of the Content without our express written permission.",
      "",
      "3. Disclaimer",
      "",
      "  3.1 The Product is provided 'as is' with a 90-day warranty, whether express or implied.",
      "",
      "  3.2 We disclaim all warranties past 90 days of initial purchase, including implied warranties of merchantability, fitness for a particular purpose, and non-infringement.",
      "",
      "  3.3 We do not warrant that the Product will be completely error-free.",
      "",
      "  3.4 We do not warrant that the results from the use of the Product or Service will be accurate or reliable.",
      "",
      "  3.5 You acknowledge that participation in physical activity carries inherent risks, and you agree to assume full responsibility for any and all risks associated with your use of the Service.",
      "",
      "4. Limitation of Liability",
      "",
      "  4.1 We will not be liable for any damages arising out of or related to your use of the Service.",
      "",
      "  4.2 This includes, but is not limited to, direct, indirect, incidental, consequential, punitive, and special damages.",
      "",
      "5. Indemnification",
      "",
      "  5.1 You agree to indemnify and hold harmless 5th Round Cardio, LLC, its officers, directors, employees, contractors, agents, and licensors from any claims, losses, damages, liabilities, including attorney's fees, arising out of or related to your use of the Service.",
      "",
      "6. Governing Law",
      "",
      "  6.1 These Terms shall be governed by and construed in accordance with the laws of the State of California.",
      "",
      "  6.2 5th Round Cardio adheres to all California governing business laws and practices.",
      "",
      "7. Dispute Resolution",
      "",
      "  7.1 Any dispute arising out of or relating to these Terms or your use of the Product shall be resolved in accordance with the rules of the American Arbitration Association ('AAA').",
      "",
      "  7.2 The arbitration shall be held in Long Beach, CA.",
      "",
      "  7.3 The arbitral award shall be binding and final and may be entered as a judgment in any court of competent jurisdiction.",
      "",
      "8. Entire Agreement",
      "",
      "  8.1 These Terms constitute the entire agreement between you and us regarding the use of the Service.",
      "",
      "9. Severability",
      "",
      "  9.1 If any provision of these Terms is held to be invalid or unenforceable, such provision shall be struck and the remaining provisions shall remain in full force and effect.",
      "",
      "10. Waiver",
      "",
      "  10.1 Our failure to enforce any provision of these Terms shall not be construed as a waiver of such provision or any other provision of these Terms.",
      "",
      "11. Notices",
      "",
      "  11.1 All notices and communications hereunder shall be in writing and deemed duly given when delivered personally, sent by certified or registered mail, or sent by overnight courier to 5th Round Cardio, LLC, 12551 E Carson Street, Hawaiian Gardens CA 90716.",
      "",
      "12. Contact Us",
      "",
      "  If you have any questions about these Terms, please contact us at 5throundcardio@gmail.com.",
      "",
      "5th Round Cardio Privacy Policy",
      "",
      "Effective Date: 6/26/24",
      "",
      "1. Information We Collect",
      "",
      "  1.1 We collect information you provide directly to us when you place an order, sign up for marketing, participate in communities, or contact customer support.",
      "",
      "2. Use of Information",
      "",
      "  2.1 We use the information to process orders, provide support, personalize your experience, send marketing communications (with your permission), and comply with legal obligations.",
      "",
      "3. Sharing of Information",
      "",
      "  3.1 We do not share, rent, lease, or sell your personal information to third parties for their independent use or benefit.",
      "",
      "  3.2 We may disclose your information as required by law to protect our rights, property, or the safety of others.",
      "",
      "4. Security",
      "",
      "  4.1 We take reasonable steps to protect your information using secure servers, encryption technology, and access controls.",
      "",
      "5. Your Choices",
      "",
      "  5.1 You can opt out of marketing communications or manage your preferences through your account settings.",
      "",
      "6. Children's Privacy",
      "",
      "  6.1 We do not knowingly collect personal information from children under 13.",
      "",
      "7. Changes to this Privacy Policy",
      "",
      "  7.1 We may update this Privacy Policy from time to time and notify you by posting the new policy on our website.",
      "",
      "8. Contact Us",
      "",
      "  If you have any questions about this Privacy Policy, please contact us at 5throundcardio@gmail.com.",
    ],
  },
  products: [
    {
      name: "The Middle Weight",
      description: [
        "Experience the durability and performance of our Middleweight Treadmill, designed for intense workouts and heavy use. With a rugged design and an added resistance dial, this treadmill offers customizable intensity, making it perfect for universities/colleges, apartment complexes, and fitness centers.",
        "The Middleweight Treadmill is engineered to withstand rigorous training sessions while providing a challenging workout experience. Its durable construction and versatility make it an ideal choice for facilities seeking reliable and high-performance cardio equipment.",
      ],
      cost: 2250,
      glbUrl: config.assetBaseUrl + "/5rc/treadmill-0/3d.glb",
      images: [
        {
          src: config.assetBaseUrl + "/5rc/treadmill-0/img-0.webp",
        },
        {
          src: config.assetBaseUrl + "/5rc/treadmill-0/img-1.webp",
        },
        {
          src: config.assetBaseUrl + "/5rc/treadmill-0/img-2.webp",
        },
        {
          src: config.assetBaseUrl + "/5rc/treadmill-0/img-3.webp",
        },
      ],
    },
    {
      name: "The Executive",
      description: [
        "The pinnacle of sophistication and functionality in the world of cardio equipment. Crafted with precision and engineered for excellence, this self-powered treadmill redefines your workout experience with its unique blend of style and innovation.",
        'Elevate your fitness routine with the seamless synergy of modern technology and timeless design. "The Executive" features stunning wooden accents that exude elegance and refinement, making it a statement piece in any home or commercial gym.',
      ],
      cost: 2000,
      glbUrl: config.assetBaseUrl + "/5rc/treadmill-1/3d.glb",
      images: [
        {
          src: config.assetBaseUrl + "/5rc/treadmill-1/img-0.webp",
        },
        {
          src: config.assetBaseUrl + "/5rc/treadmill-1/img-1.webp",
        },
        {
          src: config.assetBaseUrl + "/5rc/treadmill-1/img-2.webp",
        },
        {
          src: config.assetBaseUrl + "/5rc/treadmill-1/img-3.webp",
        },
      ],
    },
    {
      name: "The Heavyweight",
      description: [
        "th Round Cardio proudly presents ‘The Heavyweight’ treadmill. This powerhouse features a fixed 7-degree incline designed to push even the most advanced athletes to their limits. Athletes and trainers have hailed it as the ultimate masochistic training tool, ideal for elevating cardio endurance and overall work capacity.",
      ],
      cost: 3000,
      glbUrl: config.assetBaseUrl + "/5rc/treadmill-2/3d.glb",
      images: [
        {
          src: config.assetBaseUrl + "/5rc/treadmill-2/img-0.webp",
        },
        {
          src: config.assetBaseUrl + "/5rc/treadmill-2/img-1.webp",
        },
        {
          src: config.assetBaseUrl + "/5rc/treadmill-2/img-2.webp",
        },
        {
          src: config.assetBaseUrl + "/5rc/treadmill-2/img-3.webp",
        },
      ],
    },
  ],
};
export default assets;
